//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsMarried { get; set; }
        public Nullable<Gender> Gender { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
    }
}
